/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package in.sarvshiksha.cms.logic;

import in.sarvshiksha.cms.constant.Messages;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class IndexPage extends javax.swing.JFrame {

    /**
     * Creates new form introduction
     */
    private final CmsConfiguration cmsConfiguration;

    public IndexPage(CmsConfiguration cmsConfiguration) {
        this.cmsConfiguration = cmsConfiguration;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 51));

        jLabel1.setFont(new java.awt.Font("Snap ITC", 0, 36)); // NOI18N
        jLabel1.setText("Hello guyz, This is CMS");

        skipTourButton.setBackground(new java.awt.Color(255, 255, 51));
        skipTourButton.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        skipTourButton.setForeground(new java.awt.Color(102, 255, 102));
        skipTourButton.setText("Skip tour");
        skipTourButton.setToolTipText("<html><font color\"red\">Skip tour if you already know about the CMS or you don't want to know about the CMS and you want to jump to the user section.</font></html> ");
        skipTourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skipTourButtonActionPerformed(evt);
            }
        });

        takeTourButton.setBackground(new java.awt.Color(255, 255, 51));
        takeTourButton.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        takeTourButton.setForeground(new java.awt.Color(102, 255, 102));
        takeTourButton.setText("Take tour");
        takeTourButton.setToolTipText("<html><font color\"red\">Take a tour of CMS to understand the function or features of CMS which help you to use the CMS in an effective manner.</font></html> ");
        takeTourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeTourButtonActionPerformed(evt);
            }
        });

        existingUserrRadioButton.setText("Existing user");
        existingUserrRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existingUserrRadioButtonActionPerformed(evt);
            }
        });

        newUserRadioButton.setText("New user");
        newUserRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(existingUserrRadioButton)
                        .addGap(64, 64, 64)
                        .addComponent(newUserRadioButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(takeTourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(219, 219, 219)
                                .addComponent(skipTourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(skipTourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(takeTourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(existingUserrRadioButton)
                    .addComponent(newUserRadioButton))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void skipTourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skipTourButtonActionPerformed
        if (existingUserrRadioButton.isSelected()) {
            dispose();
            cmsConfiguration.getLogin().setVisible(true);
        } else if (newUserRadioButton.isSelected()) {
            dispose();
            cmsConfiguration.getNewUser().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, Messages.NOTHING_SELECTED, Messages.ERROR, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_skipTourButtonActionPerformed

    private void takeTourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takeTourButtonActionPerformed
        dispose();
        cmsConfiguration.getCmsInfoPage().setVisible(true);
    }//GEN-LAST:event_takeTourButtonActionPerformed

    private void newUserRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserRadioButtonActionPerformed
        existingUserrRadioButton.setSelected(false);
    }//GEN-LAST:event_newUserRadioButtonActionPerformed

    private void existingUserrRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existingUserrRadioButtonActionPerformed
        newUserRadioButton.setSelected(false);

    }//GEN-LAST:event_existingUserrRadioButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final javax.swing.JRadioButton existingUserrRadioButton = new javax.swing.JRadioButton();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private final javax.swing.JRadioButton newUserRadioButton = new javax.swing.JRadioButton();
    private final javax.swing.JButton skipTourButton = new javax.swing.JButton();
    private final javax.swing.JButton takeTourButton = new javax.swing.JButton();
    // End of variables declaration//GEN-END:variables
}
