/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package in.sarvshiksha.cms.logic;

import in.sarvshiksha.cms.constant.Messages;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author nisch
 */
public class Supervisor extends javax.swing.JFrame {

    /**
     * Creates new form Supervisor
     */
    private final CmsConfiguration cmsConfiguration;
    private final Map<String, Map<JRadioButton, JComboBox<String>>> issueRadioDropDownMap;

    public Supervisor(CmsConfiguration cmsConfiguration) {
        this.cmsConfiguration = cmsConfiguration;
        issueRadioDropDownMap = new HashMap<>();
        init();
    }

    private void init() {
        initComponents();
        initIssueMap();
//        initializeComplaints();
    }

    private void initIssueMap() {
        issueRadioDropDownMap.put(Concern.NON_CRITICAL_TYPE.RETURN_RELATED.name(), new HashMap<>());
        issueRadioDropDownMap.put(Concern.NON_CRITICAL_TYPE.DELIVERY_RELATED.name(), new HashMap<>());
        issueRadioDropDownMap.put(Concern.CRITICAL_TYPE.OFFER_RELATED.name(), new HashMap<>());
        issueRadioDropDownMap.put(Concern.CRITICAL_TYPE.TECHNICIAN_RELATED.name(), new HashMap<>());
        issueRadioDropDownMap.put(Concern.NON_CRITICAL_TYPE.EMI_RELATED.name(), new HashMap<>());
        issueRadioDropDownMap.put(Concern.CRITICAL_TYPE.CUSTOMER_CARE_RELATED.name(), new HashMap<>());
        issueRadioDropDownMap.put(Concern.CRITICAL_TYPE.INSTALLATION_RELATED.name(), new HashMap<>());
        issueRadioDropDownMap.put(Concern.CRITICAL_TYPE.WISHMASTER_RELATED.name(), new HashMap<>());
        issueRadioDropDownMap.put(Concern.CRITICAL_TYPE.OTHER_CONCERN.name(), new HashMap<>());
        issueRadioDropDownMap.put(Concern.NON_CRITICAL_TYPE.PAYMENT_RELATED.name(), new HashMap<>());
        issueRadioDropDownMap.put(Concern.NON_CRITICAL_TYPE.ACCOUNT_RELATED.name(), new HashMap<>());

        issueRadioDropDownMap.get(Concern.NON_CRITICAL_TYPE.RETURN_RELATED.name()).put(returnRadioButton, returnConcernDropDown);
        issueRadioDropDownMap.get(Concern.NON_CRITICAL_TYPE.DELIVERY_RELATED.name()).put(deliveryRadioButton, deliveryConcernDropDown);
        issueRadioDropDownMap.get(Concern.CRITICAL_TYPE.OFFER_RELATED.name()).put(offerRadioButton, offerConcernDropDown);
        issueRadioDropDownMap.get(Concern.CRITICAL_TYPE.TECHNICIAN_RELATED.name()).put(technicianRadioButton, technicianConcerDropDown);
        issueRadioDropDownMap.get(Concern.NON_CRITICAL_TYPE.EMI_RELATED.name()).put(emiRadioButton, emiConcernDropDown);
        issueRadioDropDownMap.get(Concern.CRITICAL_TYPE.CUSTOMER_CARE_RELATED.name()).put(cceRadioButton, cceConcernDropDown);
        issueRadioDropDownMap.get(Concern.CRITICAL_TYPE.INSTALLATION_RELATED.name()).put(installationRadioButton, installationConcernDropDown);
        issueRadioDropDownMap.get(Concern.CRITICAL_TYPE.WISHMASTER_RELATED.name()).put(feRadioButton, feConcernDropDown);
        issueRadioDropDownMap.get(Concern.CRITICAL_TYPE.OTHER_CONCERN.name()).put(otherRadioButton1, otherConcernDropDown);
        issueRadioDropDownMap.get(Concern.NON_CRITICAL_TYPE.PAYMENT_RELATED.name()).put(paymentRadioButton, paymentConcernDropDown);
        issueRadioDropDownMap.get(Concern.NON_CRITICAL_TYPE.ACCOUNT_RELATED.name()).put(accountConcernRadioButton, accountConcernDropDown);
    }

    public void initializeComplaints() {
        issueRadioDropDownMap.forEach((issueId, container) -> {
            List<Concern> concerns = (List<Concern>) cmsConfiguration.getObjectFromSession(Concern.class, issueId);
            if (!concerns.isEmpty()) {
                Map.Entry<JRadioButton, JComboBox<String>> map = (Map.Entry<JRadioButton, JComboBox<String>>) container.entrySet();
                for (Concern concern : concerns) {
                    map.getValue().addItem(concern.getOderId());
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        commentBox = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        closeCaseButton = new javax.swing.JButton();
        returnConcernDropDown = new javax.swing.JComboBox<>();
        offerConcernDropDown = new javax.swing.JComboBox<>();
        installationConcernDropDown = new javax.swing.JComboBox<>();
        emiConcernDropDown = new javax.swing.JComboBox<>();
        technicianConcerDropDown = new javax.swing.JComboBox<>();
        paymentConcernDropDown = new javax.swing.JComboBox<>();
        deliveryConcernDropDown = new javax.swing.JComboBox<>();
        cceConcernDropDown = new javax.swing.JComboBox<>();
        feConcernDropDown = new javax.swing.JComboBox<>();
        otherConcernDropDown = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        logoutButton = new javax.swing.JButton();
        returnRadioButton = new javax.swing.JRadioButton();
        offerRadioButton = new javax.swing.JRadioButton();
        emiRadioButton = new javax.swing.JRadioButton();
        installationRadioButton = new javax.swing.JRadioButton();
        feRadioButton = new javax.swing.JRadioButton();
        technicianRadioButton = new javax.swing.JRadioButton();
        paymentRadioButton = new javax.swing.JRadioButton();
        deliveryRadioButton = new javax.swing.JRadioButton();
        cceRadioButton = new javax.swing.JRadioButton();
        accountConcernRadioButton = new javax.swing.JRadioButton();
        accountConcernDropDown = new javax.swing.JComboBox<>();
        otherRadioButton1 = new javax.swing.JRadioButton();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane1.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Supervisor Mode");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Get the Details and take the action");

        commentBox.setColumns(20);
        commentBox.setRows(5);
        jScrollPane2.setViewportView(commentBox);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Add Notes");

        closeCaseButton.setText("Close case");
        closeCaseButton.setToolTipText("Submit the query form here");
        closeCaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeCaseButtonActionPerformed(evt);
            }
        });

        returnConcernDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cases" }));

        offerConcernDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cases" }));

        installationConcernDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cases" }));

        emiConcernDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cases" }));

        technicianConcerDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cases" }));

        paymentConcernDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cases" }));

        deliveryConcernDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cases" }));

        cceConcernDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cases" }));

        feConcernDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cases" }));

        otherConcernDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cases" }));

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        returnRadioButton.setText("Return concerns");
        returnRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnRadioButtonActionPerformed(evt);
            }
        });

        offerRadioButton.setText("Offer concerns");
        offerRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offerRadioButtonActionPerformed(evt);
            }
        });

        emiRadioButton.setText("E.M.I concerns");
        emiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emiRadioButtonActionPerformed(evt);
            }
        });

        installationRadioButton.setText("Installation concerns");
        installationRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                installationRadioButtonActionPerformed(evt);
            }
        });

        feRadioButton.setText("F.E concerns");
        feRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feRadioButtonActionPerformed(evt);
            }
        });

        technicianRadioButton.setText("Techician concerns");
        technicianRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                technicianRadioButtonActionPerformed(evt);
            }
        });

        paymentRadioButton.setText("Payment concerns");
        paymentRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentRadioButtonActionPerformed(evt);
            }
        });

        deliveryRadioButton.setText("Delivery concerns");
        deliveryRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveryRadioButtonActionPerformed(evt);
            }
        });

        cceRadioButton.setText("CCE concerns");
        cceRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cceRadioButtonActionPerformed(evt);
            }
        });

        accountConcernRadioButton.setText("Other concerns");
        accountConcernRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountConcernRadioButtonActionPerformed(evt);
            }
        });

        accountConcernDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cases" }));

        otherRadioButton1.setText("Other concerns");
        otherRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherRadioButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(offerRadioButton)
                            .addComponent(emiRadioButton))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(offerConcernDropDown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emiConcernDropDown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(installationRadioButton)
                            .addComponent(feRadioButton)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(accountConcernRadioButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(installationConcernDropDown, javax.swing.GroupLayout.Alignment.TRAILING, 0, 129, Short.MAX_VALUE)
                            .addComponent(feConcernDropDown, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(accountConcernDropDown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(returnRadioButton)
                        .addGap(21, 21, 21)
                        .addComponent(returnConcernDropDown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(technicianRadioButton)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cceRadioButton)
                                .addComponent(deliveryRadioButton)
                                .addComponent(otherRadioButton1))
                            .addGap(2, 2, 2)))
                    .addComponent(paymentRadioButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(otherConcernDropDown, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cceConcernDropDown, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(technicianConcerDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentConcernDropDown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deliveryConcernDropDown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logoutButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(closeCaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 370, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(167, 167, 167))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(technicianRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(technicianConcerDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(returnConcernDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(returnRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(paymentRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(paymentConcernDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(offerRadioButton)
                            .addComponent(offerConcernDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emiRadioButton)
                    .addComponent(emiConcernDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deliveryRadioButton)
                    .addComponent(deliveryConcernDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(installationRadioButton)
                        .addComponent(installationConcernDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cceRadioButton)
                        .addComponent(cceConcernDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(feRadioButton)
                    .addComponent(feConcernDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(otherConcernDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(otherRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountConcernRadioButton)
                    .addComponent(accountConcernDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeCaseButton)
                    .addComponent(logoutButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeCaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeCaseButtonActionPerformed
        if (commentBox.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, Messages.NOTHING_ENTERED, Messages.ERROR, JOptionPane.ERROR_MESSAGE);
        } else if (returnConcernDropDown.getSelectedIndex() == 0 && offerConcernDropDown.getSelectedIndex() == 0 && installationConcernDropDown.getSelectedIndex() == 0 && emiConcernDropDown.getSelectedIndex() == 0 && technicianConcerDropDown.getSelectedIndex() == 0 && paymentConcernDropDown.getSelectedIndex() == 0 && deliveryConcernDropDown.getSelectedIndex() == 0 && cceConcernDropDown.getSelectedIndex() == 0 && feConcernDropDown.getSelectedIndex() == 0 && otherConcernDropDown.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, Messages.NOTHING_SELECTED, Messages.ERROR, JOptionPane.ERROR_MESSAGE);
        } else {
            Map.Entry<JRadioButton, JComboBox<String>> map = (Map.Entry<JRadioButton, JComboBox<String>>) issueRadioDropDownMap.get(getSelectedRadioButton()).entrySet();
            cmsConfiguration.deleteObject(Concern.class, map.getValue().getSelectedItem().toString());
        }

    }//GEN-LAST:event_closeCaseButtonActionPerformed

    private List<Concern> getConcerns() {
        return (List<Concern>) cmsConfiguration.getObjectFromSession(Concern.class, getSelectedRadioButton());
    }

    private String getSelectedRadioButton() {
        for (Concern.CRITICAL_TYPE issueType : Concern.CRITICAL_TYPE.values()) {
            Map.Entry<JRadioButton, JComboBox<String>> map = (Map.Entry<JRadioButton, JComboBox<String>>) issueRadioDropDownMap.get(issueType);
            if (map.getKey().isSelected()) {
                return issueType.name();
            }
        }
        for (Concern.NON_CRITICAL_TYPE issueType : Concern.NON_CRITICAL_TYPE.values()) {
            Map.Entry<JRadioButton, JComboBox<String>> map = (Map.Entry<JRadioButton, JComboBox<String>>) issueRadioDropDownMap.get(issueType);
            if (map.getKey().isSelected()) {
                return issueType.name();
            }
        }
        return null;
    }

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        JOptionPane.showMessageDialog(this, Messages.LOGOUT, Messages.INFO, JOptionPane.PLAIN_MESSAGE);
        cmsConfiguration.getLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void installationRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_installationRadioButtonActionPerformed
        this.disableOtherRadionButton((JRadioButton) evt.getSource());
        getConcerns().forEach(concern -> {
            installationConcernDropDown.addItem(String.valueOf(concern.getIssueId()));
        });
    }//GEN-LAST:event_installationRadioButtonActionPerformed

    private void returnRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnRadioButtonActionPerformed
        this.disableOtherRadionButton((JRadioButton) evt.getSource());
        getConcerns().forEach(concern -> {
            returnConcernDropDown.addItem(String.valueOf(concern.getIssueId()));
        });
    }//GEN-LAST:event_returnRadioButtonActionPerformed

    private void disableOtherRadionButton(JRadioButton issueRadioButton) {
        for (Concern.CRITICAL_TYPE issueType : Concern.CRITICAL_TYPE.values()) {
            issueRadioDropDownMap.get(issueType).keySet().forEach(issue -> {
                if (!issueRadioButton.equals(issue)) {
                    issue.setSelected(Boolean.FALSE);
                }
            });
        }
        for (Concern.NON_CRITICAL_TYPE issueType : Concern.NON_CRITICAL_TYPE.values()) {
            issueRadioDropDownMap.get(issueType).keySet().forEach(issue -> {
                if (!issueRadioButton.equals(issue)) {
                    issue.setSelected(Boolean.FALSE);
                }
            });
        }

    }

    private void offerRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offerRadioButtonActionPerformed
        this.disableOtherRadionButton((JRadioButton) evt.getSource());
        getConcerns().forEach(concern -> {
            offerConcernDropDown.addItem(String.valueOf(concern.getIssueId()));
        });
    }//GEN-LAST:event_offerRadioButtonActionPerformed

    private void emiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emiRadioButtonActionPerformed
        this.disableOtherRadionButton((JRadioButton) evt.getSource());
        getConcerns().forEach(concern -> {
            emiConcernDropDown.addItem(String.valueOf(concern.getIssueId()));
        });
    }//GEN-LAST:event_emiRadioButtonActionPerformed

    private void feRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feRadioButtonActionPerformed
        this.disableOtherRadionButton((JRadioButton) evt.getSource());
        getConcerns().forEach(concern -> {
            feConcernDropDown.addItem(String.valueOf(concern.getIssueId()));
        });
    }//GEN-LAST:event_feRadioButtonActionPerformed

    private void technicianRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_technicianRadioButtonActionPerformed
        this.disableOtherRadionButton((JRadioButton) evt.getSource());
        getConcerns().forEach(concern -> {
            technicianConcerDropDown.addItem(String.valueOf(concern.getIssueId()));
        });
    }//GEN-LAST:event_technicianRadioButtonActionPerformed

    private void paymentRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentRadioButtonActionPerformed
        this.disableOtherRadionButton((JRadioButton) evt.getSource());
        getConcerns().forEach(concern -> {
            paymentConcernDropDown.addItem(String.valueOf(concern.getIssueId()));
        });
    }//GEN-LAST:event_paymentRadioButtonActionPerformed

    private void deliveryRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveryRadioButtonActionPerformed
        this.disableOtherRadionButton((JRadioButton) evt.getSource());
        getConcerns().forEach(concern -> {
            deliveryConcernDropDown.addItem(String.valueOf(concern.getIssueId()));
        });
    }//GEN-LAST:event_deliveryRadioButtonActionPerformed

    private void cceRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cceRadioButtonActionPerformed
        this.disableOtherRadionButton((JRadioButton) evt.getSource());
        getConcerns().forEach(concern -> {
            cceConcernDropDown.addItem(String.valueOf(concern.getIssueId()));
        });
    }//GEN-LAST:event_cceRadioButtonActionPerformed

    private void accountConcernRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountConcernRadioButtonActionPerformed
        this.disableOtherRadionButton((JRadioButton) evt.getSource());
        getConcerns().forEach(concern -> {
            accountConcernDropDown.addItem(String.valueOf(concern.getIssueId()));
        });
    }//GEN-LAST:event_accountConcernRadioButtonActionPerformed

    private void otherRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherRadioButton1ActionPerformed
        this.disableOtherRadionButton((JRadioButton) evt.getSource());
        getConcerns().forEach(concern -> {
            otherConcernDropDown.addItem(String.valueOf(concern.getIssueId()));
        });
    }//GEN-LAST:event_otherRadioButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> accountConcernDropDown;
    private javax.swing.JRadioButton accountConcernRadioButton;
    private javax.swing.JComboBox<String> cceConcernDropDown;
    private javax.swing.JRadioButton cceRadioButton;
    private javax.swing.JButton closeCaseButton;
    private javax.swing.JTextArea commentBox;
    private javax.swing.JComboBox<String> deliveryConcernDropDown;
    private javax.swing.JRadioButton deliveryRadioButton;
    private javax.swing.JComboBox<String> emiConcernDropDown;
    private javax.swing.JRadioButton emiRadioButton;
    private javax.swing.JComboBox<String> feConcernDropDown;
    private javax.swing.JRadioButton feRadioButton;
    private javax.swing.JComboBox<String> installationConcernDropDown;
    private javax.swing.JRadioButton installationRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JComboBox<String> offerConcernDropDown;
    private javax.swing.JRadioButton offerRadioButton;
    private javax.swing.JComboBox<String> otherConcernDropDown;
    private javax.swing.JRadioButton otherRadioButton1;
    private javax.swing.JComboBox<String> paymentConcernDropDown;
    private javax.swing.JRadioButton paymentRadioButton;
    private javax.swing.JComboBox<String> returnConcernDropDown;
    private javax.swing.JRadioButton returnRadioButton;
    private javax.swing.JComboBox<String> technicianConcerDropDown;
    private javax.swing.JRadioButton technicianRadioButton;
    // End of variables declaration//GEN-END:variables
}
