/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package in.sarvshiksha.cms.datamodel;

import in.sarvshiksha.cms.constant.Messages;
import in.sarvshiksha.cms.logic.CmsConfiguration;
import in.sarvshiksha.cms.logic.Concern;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author nisch
 */
public class Issue extends javax.swing.JFrame {

    /**
     * Creates new form Technician_related_issue
     */
    private final CmsConfiguration cmsConfiguration;
    private int issueId;
    private ProductDescription productDescription;

    public Issue(CmsConfiguration cmsConfiguration) {
        this.cmsConfiguration = cmsConfiguration;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        issueTitleField = new java.awt.Label();
        jSeparator1 = new javax.swing.JSeparator();
        chooseSubConcernTitle = new java.awt.Label();
        issueDropDown = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        commentBox = new javax.swing.JTextArea();
        submitButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        backButton = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        issueTitleField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        issueTitleField.setText("Techinician related issue");

        chooseSubConcernTitle.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        chooseSubConcernTitle.setText("Choose the issue");

        issueDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a reason", "Techincian_date_breached", "Technician_alingment", "Technician_behaviour_issue", "Techinician_didn't_check_the_product_appropraitely", " " }));

        commentBox.setColumns(20);
        commentBox.setRows(5);
        jScrollPane1.setViewportView(commentBox);

        submitButton.setText("Submit");
        submitButton.setToolTipText("Submit the query form here");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        backButton.setLabel("<-");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(issueDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(issueTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(logoutButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(chooseSubConcernTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(issueTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chooseSubConcernTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(issueDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(logoutButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void init(String issueTitle, ProductDescription productDescription, List<String> issues) {
        this.issueTitleField.setText(issueTitle);
        this.productDescription = productDescription;
        this.addIssuesInDropDown(issues);
        this.setVisible(true);
    }

    private void addIssuesInDropDown(List<String> issues) {
        issues.forEach(issue -> {
            issueDropDown.addItem(issue);
        });
    }

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        if (issueDropDown.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, Messages.NOTHING_SELECTED, Messages.ERROR, JOptionPane.ERROR_MESSAGE);
        } else if ((commentBox.getText()).length() == 0) {
            JOptionPane.showMessageDialog(this, Messages.NO_COMMENT, Messages.ERROR, JOptionPane.WARNING_MESSAGE);
        } else {
            cmsConfiguration.setObject(new Concern(issueId, productDescription.getOderId(), productDescription.getCustomerName(), productDescription.getMobileNumber(), new Date(), new Date(), null, issueDropDown.getSelectedItem().toString(), commentBox.getText()));
            JOptionPane.showMessageDialog(this, Messages.SUCCESS_MESSAGE, Messages.INFO, JOptionPane.PLAIN_MESSAGE);
            dispose();
            cmsConfiguration.getAgent().setVisible(true);
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        JOptionPane.showMessageDialog(this, Messages.LOGOUT, Messages.INFO, JOptionPane.PLAIN_MESSAGE);
        dispose();
        cmsConfiguration.getLogin().setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        dispose();
        cmsConfiguration.getAgent().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button backButton;
    private java.awt.Label chooseSubConcernTitle;
    private javax.swing.JTextArea commentBox;
    private javax.swing.JComboBox<String> issueDropDown;
    private java.awt.Label issueTitleField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
